var ENUM = function() {};

ENUM.Role = {
	PUBLISH : 'PUBLISH',
	ANALYSIS : 'ANALYSIS',
	ADMIN : 'ADMIN',
	SYSTEM : 'SYSTEM'
};

ENUM.TaskStatus = {
	EDITING   : 'EDITING',
	PUBLISHED : 'PUBLISHED',
	FINISHED  : 'FINISHED'
};