var ENUM = function() {
};

ENUM.Role = {
	PUBLISH : 'PUBLISH',
	ANALYSIS : 'ANALYSIS',
	ADMIN : 'ADMIN',
	SYSTEM : 'SYSTEM'
};

ENUM.TaskStatus = {
	EDITING : 'EDITING',
	PUBLISHED : 'PUBLISHED',
	FINISHED : 'FINISHED'
};

ENUM.TaskAction = {
	SAVE : 'SAVE',
	DELETE : 'DELETE',
	PUBLISH : 'PUBLISH',
	COPY : 'COPY',
	ADJUST : 'ADJUST',
	CANCEL : 'CANCEL'
};

ENUM.BatchAction = {
	SAVE : 'SAVE',
	DELETE : 'DELETE',
	ADJUST : 'ADJUST'
};

ENUM.SubTaskAction = {
	SAVE : 'SAVE',
	DELETE : 'DELETE'
};